# Generated by Django 5.2.16 on 2026-07-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('upwork', 'Upwork'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter / X'), ('telegram', 'Telegram'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('website', 'Website'), ('email', 'Email'), ('phone', 'Phone')], default='github', max_length=20),
        ),
    ]
